services:
  postgres:
    image: postgres:16
    container_name: academic-repository-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: academic_repository
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d academic_repository -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
